chn-challenger/one_maths

- app/assets/javascripts/application.js
- spec/zjavascript/lesson_ajax_feature_spec.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> Empty field validation

- app/controllers/catalogue_controller.rb
- app/controllers/images_controller.rb
- app/views/catalogue/index.html.erb
- db/migrate/20161101132344_change_tags_name_to_unique.rb
- db/schema.rb
- spec/non_js_tests/features/catalogue_feature_spec.rb
> Complete feature working and tested

- app/views/catalogue/edit.html.erb
- app/views/catalogue/exam_questions.html.erb
- app/views/catalogue/new.html.erb
> Bug fix-adding edit links to exam questions in exam_questions view

- app/controllers/questions_controller.rb
- app/models/question.rb
- db/schema.rb
- spec/general_helpers.rb
- spec/non_js_tests/models/question_spec.rb
> 41 delete dependent

- app/assets/javascripts/application.js
- app/views/lessons/new_question.html.erb
> Feature complete un/check all boxes for lesson

- app/actions/tex_parser.rb
- db/schema.rb
> Bug fixed last question gets added and new lines are stripped

- app/assets/javascripts/application.js
- app/assets/stylesheets/questions.scss
- app/controllers/lessons_controller.rb
- app/controllers/questions_controller.rb
- app/models/image.rb
- app/models/question.rb
- app/views/questions/edit.html.erb
- app/views/questions/index.html.erb
- app/views/questions/new.html.erb
- app/views/shared/_student_lesson_details.html.erb
- db/migrate/20161116220113_add_question_to_images.rb
- db/schema.rb
- spec/general_helpers.rb
- spec/non_js_tests/features/questions_feature_spec.rb
> 43 question image

- app/actions/tex_parser.rb
- spec/fixtures/Questions_Differentiation.tex
- spec/non_js_tests/actions/tex_parser_spec.rb
> Tex parser updated to consider answer types

- app/assets/javascripts/zchoices_checkbox.js
- app/controllers/catalogue_controller.rb
- app/helpers/catalogue_helper.rb
- db/schema.rb
> 69 and on tags

- app/models/question.rb
- spec/non_js_tests/features/questions_feature_spec.rb
> EXP no longer updated upon question deletion

- app/helpers/input_processor_helper.rb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/helpers/input_processor_helper_spec.rb
- spec/non_js_tests/models/topic_spec.rb
> WIP extended inequality support and split with "or"

- app/helpers/input_processor_helper.rb
- spec/non_js_tests/helpers/input_processor_helper_spec.rb
> 82 inequality up

- app/helpers/topics_helper.rb
- app/views/shared/_student_topic_question_details.html.erb
- app/views/shared/_topic_lessons.html.erb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/non_js_tests/helpers/topic_helper_spec.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> WIP topics can be unlocked with specs

- Gemfile
- Gemfile.lock
- app/controllers/concerns/recycle_questions.rb
- app/controllers/questions_controller.rb
- app/models/question_reset.rb
- app/models/user.rb
- db/migrate/20170104142725_create_question_resets.rb
- db/schema.rb
- spec/helpers/general_helpers.rb
- spec/helpers/lesson_spec_helper.rb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/zjavascript/lesson_ajax_feature_spec.rb
> Feature complete specs added

- app/controllers/answered_questions_controller.rb
- app/controllers/questions_controller.rb
- app/models/lesson.rb
- app/views/answered_questions/answered_questions.html.erb
- spec/helpers/general_helpers.rb
- spec/non_js_tests/features/courses_feature_spec.rb
- spec/non_js_tests/features/jobs_feature_spec.rb
- spec/non_js_tests/features/support_system_feature_spec.rb
- spec/non_js_tests/features/tester_feature_spec.rb
- spec/rails_helper.rb
- spec/zjavascript/support_system_ajax_feature_spec.rb
> 109 tester bug

- app/controllers/lessons_controller.rb
- app/controllers/questions_controller.rb
- app/helpers/topics_helper.rb
- app/models/lesson.rb
- app/models/question.rb
- spec/helpers/general_helpers.rb
- spec/non_js_tests/features/jobs_feature_spec.rb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/features/support_system_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/non_js_tests/helpers/topic_helper_spec.rb
- spec/non_js_tests/models/student_lesson_exp_spec.rb
- spec/non_js_tests/models/student_topic_exp_spec.rb
- spec/rails_helper.rb
- spec/zjavascript/lesson_ajax_feature_spec.rb
- spec/zjavascript/support_system_ajax_feature_spec.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> Auto pass exp

- app/controllers/questions_controller.rb
- app/helpers/questions_helper.rb
- app/models/answered_question.rb
- app/models/current_question.rb
- app/models/lesson.rb
- app/models/user.rb
- app/views/shared/_header.html.erb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- db/schema.rb
- lib/loggers/current_question_logger.rb
> Current questions logger introduced and validation added

- app/models/lesson.rb
- spec/non_js_tests/models/lesson_spec.rb
> Returns first order if question order no longer exists in lesson

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/variables.scss
- app/controllers/concerns/ticket_support.rb
- app/controllers/tickets_controller.rb
- app/helpers/tickets_helper.rb
- app/views/tickets/index.html.erb
> Improved ticket query added styling and confirmed users can closed tickets

- app/controllers/concerns/input_processor_support.rb
- app/helpers/questions_helper.rb
- spec/non_js_tests/concerns/input_processor_support_spec.rb
> Split inequalities by `or` or `,`

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/nav.scss
- app/views/jobs/index.html.erb
- app/views/shared/_header.html.erb
- spec/helpers/general_helpers.rb
- spec/non_js_tests/features/jobs_feature_spec.rb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/non_js_tests/features/support_system_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/rails_helper.rb
- spec/zjavascript/support_system_ajax_feature_spec.rb
Fix erratic spec failures... SSL protocols updated for PhantomJS refer to `rails_helper.rb` for details
> Dropdown menu updated, removed js listeners

- app/controllers/questions_controller.rb
- app/helpers/questions_helper.rb
- app/models/answered_question.rb
- app/models/lesson.rb
- app/views/lessons/show.js.erb
- app/views/shared/_student_lesson_details.html.erb
- app/views/shared/_student_topic_question_details.html.erb
- app/views/topics/show.js.erb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/zjavascript/lesson_ajax_feature_spec.rb
> 117 lesson exp lim

- app/assets/javascripts/application.js
- app/assets/stylesheets/topics.scss
- app/controllers/topics_controller.rb
- app/models/question.rb
- app/views/topics/new_question.html.erb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/rails_helper.rb
- spec/support/wait_for_ajax.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> Topic questions can be added with scope to topic and lessons

- app/models/answered_question.rb
- app/views/lessons/show.js.erb
- db/migrate/20170130131318_add_unique_index_to_answered_questions.rb
- db/schema.rb
> DB validation for question user and lesson for Answered Questions

- .rake_tasks~
- app/actions/tex_parser.rb
- app/assets/stylesheets/answers.scss
- app/assets/stylesheets/questions.scss
- app/controllers/answers_controller.rb
- app/controllers/questions_controller.rb
- app/models/answer.rb
- app/views/answers/edit.html.erb
- app/views/answers/new.html.erb
- app/views/questions/index.html.erb
- app/views/shared/_question_edit.html.erb
- app/views/shared/_student_lesson_details.html.erb
- app/views/shared/_student_topic_question_details.html.erb
- db/migrate/20170130160644_add_order_column_to_answers.rb
- db/schema.rb
- lib/tasks/set_order_to_answer.rake
- spec/non_js_tests/features/answers_feature_spec.rb
- spec/non_js_tests/features/tester_feature_spec.rb
> 140 order to answers

- app/assets/javascripts/application.js
- app/assets/javascripts/settings.coffee
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/settings.scss
- app/controllers/settings/settings_controller.rb
- app/helpers/answers_choices_helper.rb
- app/helpers/answers_helper.rb
- app/helpers/settings_helper.rb
- app/models/topic.rb
- app/views/answers/new.html.erb
- app/views/layouts/application.html.erb
- app/views/questions/index.html.erb
- app/views/settings/settings/create.html.erb
- app/views/settings/settings/index.html.erb
- app/views/settings/settings/show.html.erb
- app/views/settings/settings/update.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_student_lesson_details.html.erb
- app/views/shared/_student_topic_question_details.html.erb
- config/one_maths_config.yml
- config/one_maths_hints.yml
- config/routes.rb
- spec/helpers/general_helpers.rb
- spec/non_js_tests/features/answers_feature_spec.rb
- spec/zjavascript/lesson_ajax_feature_spec.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> 138 settings hints

- .rspec
- app/helpers/topics_helper.rb
- app/views/shared/_student_topic_question_details.html.erb
- spec/helpers/general_helpers.rb
- spec/zjavascript/topic_ajax_feature_spec.rb
> Topic displayes questions properly and pools from lesson

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/teachers.scss
- app/views/shared/_header.html.erb
- app/views/teachers/index.html.erb
- app/views/teachers/invitation.html.erb
Styling added to an invitation and scoping added for teacher view.
> 143 homework

- app/controllers/topics_controller.rb
- app/models/user.rb
- app/views/management/student_manager.html.erb
- app/views/shared/_student_topic_question_details.html.erb
Topic choices/question images are displayed properly.
> Topic question choices images are displayed

- app/controllers/concerns/input_processor_support.rb
> Non-UTF 8 characters are filtered and replaced with space

- app/helpers/questions_helper.rb
> Lesson capped at pass_exp

- app/assets/javascripts/application.js
- app/assets/stylesheets/units.scss
- app/views/layouts/application.html.erb
- app/views/lessons/show.js.erb
> Global listener on video added no longer loaded dynamically

- app/views/layouts/pages.html.erb
Closes #154 
Additional Setup needed for Heap Analytics to work
> Heap analytics tracker added pending landing page launch

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/management.scss
- app/views/lessons/show.js.erb
- app/views/units/show.html.erb
Hi Joe,
Please have a look whether this is the expected behaviour and how it should look like.
> Add modal when answering unit questions

- .rspec
- app/assets/javascripts/application.js
- app/assets/javascripts/devise.js
- app/controllers/answers_controller.rb
- app/controllers/application_controller.rb
- app/controllers/choices_controller.rb
- app/controllers/images_controller.rb
- app/controllers/jobs_controller.rb
- app/controllers/management_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/teachers_controller.rb
- app/views/shared/_header.html.erb
- spec/non_js_tests/features/answers_feature_spec.rb
- spec/non_js_tests/features/choices_feature_spec.rb
- spec/non_js_tests/features/courses_feature_spec.rb
- spec/non_js_tests/features/jobs_feature_spec.rb
- spec/non_js_tests/features/lessons_feature_spec.rb
- spec/non_js_tests/features/pages_feature_spec.rb
- spec/non_js_tests/features/questions_feature_spec.rb
- spec/non_js_tests/features/support_system_feature_spec.rb
- spec/non_js_tests/features/tester_feature_spec.rb
- spec/non_js_tests/features/topics_feature_spec.rb
- spec/non_js_tests/features/users_feature_spec.rb
- vendor/assets/javascripts/snoox/functions.js
> JS refactores specs passing
